[[scenario]]
name = "session-write-c32"
url = "{{ base_url }}/session/write"
connections = 32
max_throughput = true
duration = {{ duration_secs }}
warmup = {{ warmup_secs }}

[scenario.headers]
Cookie = "sid=00000000000000001111111111111111.8087963058b4ac62ee1bed1887ad691ca6c5af4fe478ceff97e8cb39e712b0bc"
